name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  image:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The jekyll/builder was replaced by the action jekyll-build-pages
        docker-image: [ 'sylhare/jekyll' ]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./output"
      - name: Build with Docker
        continue-on-error: true
        run: |
          cd assets && docker build .
      - name: Build the site in the container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          ${{ matrix.docker-image }}:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      - name: Pull docker images
        continue-on-error: true
        run: |
          docker pull sylhare/type-on-strap
          docker pull sylhare/jekyll